const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Behaviors.Fade,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Text.Acts.MoveToLayer,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Plugins.System.Acts.Wait
	];
};
self.C3_JsPropNameTable = [
	{Background: 0},
	{isFound: 0},
	{HintText: 0},
	{ImageFrame: 0},
	{ImageFrame2: 0},
	{InventoryFrame: 0},
	{Clue_Suit: 0},
	{Clue_Backpack: 0},
	{Clue_Paper: 0},
	{Popup_Background: 0},
	{Popup_ClueImage2: 0},
	{Popup_HintText: 0},
	{Button_Close: 0},
	{Touch: 0},
	{StartScreen: 0},
	{Button_Start: 0},
	{Background_Default: 0},
	{Suspect_Arisa: 0},
	{Suspect_Tadsapong: 0},
	{Suspect_Winai: 0},
	{Button_Confirm: 0},
	{Button_Next: 0},
	{Fade: 0},
	{Title: 0},
	{Title_Text: 0},
	{WinScreen: 0},
	{LoseScreen: 0},
	{ClueCounter_Text: 0},
	{Popup_ClueImage: 0},
	{Backdrop: 0},
	{Disappointed: 0},
	{ImageFrame3: 0},
	{Picture_Frame: 0},
	{Wine_Glass: 0},
	{Phone: 0},
	{Tranquillizer: 0},
	{MessageText: 0},
	{Rubber_Gloves: 0},
	{Popup_ClueImage3: 0},
	{Audio: 0},
	{Message_Text: 0},
	{Knife: 0},
	{Win_Text: 0},
	{Lose_Text: 0},
	{Magnifying_Glass: 0},
	{Button_StartAgain: 0},
	{Button_Home: 0},
	{Result_Text: 0},
	{BrokenWineBottle: 0},
	{Footprint: 0},
	{Message_Background: 0},
	{FadeOverlay: 0},
	{Credit: 0},
	{Website: 0},
	{WebsiteLink_Button: 0},
	{AllClues: 0},
	{AllClues2: 0},
	{Message: 0},
	{HintsFound: 0},
	{TotalClues: 0},
	{IsPopupOpen: 0},
	{IsMessageActive: 0},
	{SelectedKiller: 0},
	{TrueKiller: 0},
	{FullText: 0},
	{CurrentCharIndex: 0},
	{RevealSpeed: 0},
	{IsRevealing: 0}
];

self.InstanceType = {
	Background: class extends self.ISpriteInstance {},
	Clue_Suit: class extends self.ISpriteInstance {},
	Clue_Backpack: class extends self.ISpriteInstance {},
	Clue_Paper: class extends self.ISpriteInstance {},
	Popup_Background: class extends self.ISpriteInstance {},
	Popup_ClueImage2: class extends self.ISpriteInstance {},
	Popup_HintText: class extends self.ITextInstance {},
	Button_Close: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	StartScreen: class extends self.ISpriteInstance {},
	Button_Start: class extends self.ISpriteInstance {},
	Background_Default: class extends self.ISpriteInstance {},
	Suspect_Arisa: class extends self.ISpriteInstance {},
	Suspect_Tadsapong: class extends self.ISpriteInstance {},
	Suspect_Winai: class extends self.ISpriteInstance {},
	Button_Confirm: class extends self.ISpriteInstance {},
	Button_Next: class extends self.ISpriteInstance {},
	Title: class extends self.ISpriteInstance {},
	Title_Text: class extends self.ITextInstance {},
	WinScreen: class extends self.ISpriteInstance {},
	LoseScreen: class extends self.ISpriteInstance {},
	ClueCounter_Text: class extends self.ITextInstance {},
	Popup_ClueImage: class extends self.ISpriteInstance {},
	Backdrop: class extends self.ISpriteInstance {},
	Disappointed: class extends self.ISpriteInstance {},
	Picture_Frame: class extends self.ISpriteInstance {},
	Wine_Glass: class extends self.ISpriteInstance {},
	Phone: class extends self.ISpriteInstance {},
	Tranquillizer: class extends self.ISpriteInstance {},
	Rubber_Gloves: class extends self.ISpriteInstance {},
	Popup_ClueImage3: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Message_Text: class extends self.ITextInstance {},
	Knife: class extends self.ISpriteInstance {},
	Win_Text: class extends self.ISpriteInstance {},
	Lose_Text: class extends self.ISpriteInstance {},
	Magnifying_Glass: class extends self.ISpriteInstance {},
	Button_StartAgain: class extends self.ISpriteInstance {},
	Button_Home: class extends self.ISpriteInstance {},
	Result_Text: class extends self.ITextInstance {},
	BrokenWineBottle: class extends self.ISpriteInstance {},
	Footprint: class extends self.ISpriteInstance {},
	Message_Background: class extends self.ISpriteInstance {},
	FadeOverlay: class extends self.ISpriteInstance {},
	Credit: class extends self.ISpriteInstance {},
	Website: class extends self.IInstance {},
	WebsiteLink_Button: class extends self.ISpriteInstance {},
	AllClues: class extends self.ISpriteInstance {},
	AllClues2: class extends self.ISpriteInstance {},
	Message: class extends self.ISpriteInstance {}
}